name: 'SonarQube Scan'

on:
#   push:
#     branches:
#       - main

    workflow_dispatch:

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0